//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypeLess.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TypeLess.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be true.
        /// </summary>
        internal static string BoolIsFalse {
            get {
                return ResourceManager.GetString("BoolIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be false.
        /// </summary>
        internal static string BoolIsTrue {
            get {
                return ResourceManager.GetString("BoolIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not contain {0}.
        /// </summary>
        internal static string ContainsItems {
            get {
                return ResourceManager.GetString("ContainsItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not contain key {0}.
        /// </summary>
        internal static string ContainsKey {
            get {
                return ResourceManager.GetString("ContainsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must contain more than {0} items.
        /// </summary>
        internal static string ContainsLessThan {
            get {
                return ResourceManager.GetString("ContainsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must contain less than {0} items.
        /// </summary>
        internal static string ContainsMoreThan {
            get {
                return ResourceManager.GetString("ContainsMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must contain text {0}.
        /// </summary>
        internal static string DoesNotContain {
            get {
                return ResourceManager.GetString("DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must contain alpha numeric characters.
        /// </summary>
        internal static string DoesNotContainAlphaChars {
            get {
                return ResourceManager.GetString("DoesNotContainAlphaChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must contain at least 1 digit.
        /// </summary>
        internal static string DoesNotContainDigit {
            get {
                return ResourceManager.GetString("DoesNotContainDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must contain {0}.
        /// </summary>
        internal static string DoesNotContainItems {
            get {
                return ResourceManager.GetString("DoesNotContainItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must contain key {0}.
        /// </summary>
        internal static string DoesNotContainKey {
            get {
                return ResourceManager.GetString("DoesNotContainKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must end with text {0}.
        /// </summary>
        internal static string DoesNotEndWith {
            get {
                return ResourceManager.GetString("DoesNotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must match pattern {0}.
        /// </summary>
        internal static string DoesNotMatch {
            get {
                return ResourceManager.GetString("DoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must start with text {0}.
        /// </summary>
        internal static string DoesNotStartWith {
            get {
                return ResourceManager.GetString("DoesNotStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be smaller than {0}.
        /// </summary>
        internal static string IsAfter {
            get {
                return ResourceManager.GetString("IsAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be larger than {0}.
        /// </summary>
        internal static string IsBefore {
            get {
                return ResourceManager.GetString("IsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be empty.
        /// </summary>
        internal static string IsEmpty {
            get {
                return ResourceManager.GetString("IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be equal to {0}.
        /// </summary>
        internal static string IsEqualTo {
            get {
                return ResourceManager.GetString("IsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be smaller than {0}.
        /// </summary>
        internal static string IsGreaterThan {
            get {
                return ResourceManager.GetString("IsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be shorter than {0} characters.
        /// </summary>
        internal static string IsLongerThan {
            get {
                return ResourceManager.GetString("IsLongerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be zero or positive.
        /// </summary>
        internal static string IsNegative {
            get {
                return ResourceManager.GetString("IsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be equal to {0}.
        /// </summary>
        internal static string IsNotEqualTo {
            get {
                return ResourceManager.GetString("IsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be null.
        /// </summary>
        internal static string IsNotNull {
            get {
                return ResourceManager.GetString("IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection must contain &lt;name&gt;.
        /// </summary>
        internal static string IsNotPartOf {
            get {
                return ResourceManager.GetString("IsNotPartOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be a valid email address.
        /// </summary>
        internal static string IsNotValidEmail {
            get {
                return ResourceManager.GetString("IsNotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be a valid IMO number.
        /// </summary>
        internal static string IsNotValidImoNr {
            get {
                return ResourceManager.GetString("IsNotValidImoNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be a valid ISBN.
        /// </summary>
        internal static string IsNotValidISBN {
            get {
                return ResourceManager.GetString("IsNotValidISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be a valid personal number.
        /// </summary>
        internal static string IsNotValidPersonalNumber {
            get {
                return ResourceManager.GetString("IsNotValidPersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be a valid phone number.
        /// </summary>
        internal static string IsNotValidPhoneNumber {
            get {
                return ResourceManager.GetString("IsNotValidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be a valid social security number.
        /// </summary>
        internal static string IsNotValidSocialSecurityNumber {
            get {
                return ResourceManager.GetString("IsNotValidSocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt;must be a valid Swift code.
        /// </summary>
        internal static string IsNotValidSwiftCode {
            get {
                return ResourceManager.GetString("IsNotValidSwiftCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be a valid URL.
        /// </summary>
        internal static string IsNotValidUrl {
            get {
                return ResourceManager.GetString("IsNotValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be a valid zip code.
        /// </summary>
        internal static string IsNotValidZipCode {
            get {
                return ResourceManager.GetString("IsNotValidZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be within {0} and {1}.
        /// </summary>
        internal static string IsNotWithin {
            get {
                return ResourceManager.GetString("IsNotWithin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; is required.
        /// </summary>
        internal static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection must not contain &lt;name&gt;.
        /// </summary>
        internal static string IsPartOf {
            get {
                return ResourceManager.GetString("IsPartOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be zero or negative.
        /// </summary>
        internal static string IsPositive {
            get {
                return ResourceManager.GetString("IsPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be longer than {0} characters.
        /// </summary>
        internal static string IsShorterThan {
            get {
                return ResourceManager.GetString("IsShorterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be greater than {0}.
        /// </summary>
        internal static string IsSmallerThan {
            get {
                return ResourceManager.GetString("IsSmallerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be a ISBN.
        /// </summary>
        internal static string IsValidISBN {
            get {
                return ResourceManager.GetString("IsValidISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be a valid personal number.
        /// </summary>
        internal static string IsValidPersonalNumber {
            get {
                return ResourceManager.GetString("IsValidPersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be a valid phone number.
        /// </summary>
        internal static string IsValidPhoneNumber {
            get {
                return ResourceManager.GetString("IsValidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be a social security number.
        /// </summary>
        internal static string IsValidSocialSecurityNumber {
            get {
                return ResourceManager.GetString("IsValidSocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be a URL.
        /// </summary>
        internal static string IsValidUrl {
            get {
                return ResourceManager.GetString("IsValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be a zip code.
        /// </summary>
        internal static string IsValidZipCode {
            get {
                return ResourceManager.GetString("IsValidZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be within {0} and {1}.
        /// </summary>
        internal static string IsWithin {
            get {
                return ResourceManager.GetString("IsWithin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be non zero.
        /// </summary>
        internal static string IsZero {
            get {
                return ResourceManager.GetString("IsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not match pattern {0}.
        /// </summary>
        internal static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be on same day as {0}.
        /// </summary>
        internal static string NotSameDayAs {
            get {
                return ResourceManager.GetString("NotSameDayAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be on same hour as {0}.
        /// </summary>
        internal static string NotSameHourAs {
            get {
                return ResourceManager.GetString("NotSameHourAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be on same minute as {0}.
        /// </summary>
        internal static string NotSameMinuteAs {
            get {
                return ResourceManager.GetString("NotSameMinuteAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be on same month as {0}.
        /// </summary>
        internal static string NotSameMonthAs {
            get {
                return ResourceManager.GetString("NotSameMonthAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be on same second as {0}.
        /// </summary>
        internal static string NotSameSecondAs {
            get {
                return ResourceManager.GetString("NotSameSecondAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be on same week day as {0}.
        /// </summary>
        internal static string NotSameWeekDayAs {
            get {
                return ResourceManager.GetString("NotSameWeekDayAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be on same year as {0}.
        /// </summary>
        internal static string NotSameYearAs {
            get {
                return ResourceManager.GetString("NotSameYearAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be on same day as {0}.
        /// </summary>
        internal static string SameDayAs {
            get {
                return ResourceManager.GetString("SameDayAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be on same hour as {0}.
        /// </summary>
        internal static string SameHourAs {
            get {
                return ResourceManager.GetString("SameHourAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be on same minute as {0}.
        /// </summary>
        internal static string SameMinuteAs {
            get {
                return ResourceManager.GetString("SameMinuteAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be on same month as {0}.
        /// </summary>
        internal static string SameMonthAs {
            get {
                return ResourceManager.GetString("SameMonthAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be on same second as {0}.
        /// </summary>
        internal static string SameSecondAs {
            get {
                return ResourceManager.GetString("SameSecondAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be on same week day as {0}.
        /// </summary>
        internal static string SameWeekDayAs {
            get {
                return ResourceManager.GetString("SameWeekDayAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must not be on same year as {0}.
        /// </summary>
        internal static string SameYearAs {
            get {
                return ResourceManager.GetString("SameYearAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be shorter than {0:c}.
        /// </summary>
        internal static string TimeSpanIsLongerThan {
            get {
                return ResourceManager.GetString("TimeSpanIsLongerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;name&gt; must be longer than {0:c}.
        /// </summary>
        internal static string TimeSpanIsShorterThan {
            get {
                return ResourceManager.GetString("TimeSpanIsShorterThan", resourceCulture);
            }
        }
    }
}
